### ISSUE TITLE
USE IN ESPRESSIF ESP32

### ISSUE THREAD

**Issue by arturhercoles63** [sensslen/LibLanc#13]
I would like to know the compatibility of the library with the ESP32 microcontroller, both in terms of logic and hardware.

The ESP32 normally accepts voltages of 3.3V, which are different from those used in the LANC lines.

My project aims to create a gateway from VISCA to LANC and control my LANC camera through OBS using VISCA.

**Comment by sensslen** [comment]
I'm using liblanc on an esp32. If you design your hardware accordingly this is not an issue. See https://github.com/sensslen/Cgf.CameraControl.Camera for the software and https://github.com/sensslen/Cfg.CameraControl.Hardware for the hardware.

**Comment by arturhercoles63** [comment]
Thanks for your help. this is what I need
