### ISSUE TITLE
Videostart?

### ISSUE THREAD

**Issue by pcace** [sensslen/LibLanc#3]
Hi There, is there any way to use the library to start video recording?

Cheers and thanks!

**Comment by sensslen** [comment]
I guess there is nothing that prevents you from doing so. At the moment this in not a feature that is implemented. However, Pull requests are welcome. There is a very nice writeup on the lanc commands here: http://www.boehmel.de/lanc.htm

Be aware that lanc does not normally accept the first command you send it right away so in case of start recording you might think about how to get feedback that the command has been accepted.
