### ISSUE TITLE
Wiring Diagram?

### ISSUE THREAD

**Issue by mattv8** [sensslen/LibLanc#4]
There are many examples of wiring diagrams for an Arduino to Sony LANC, usually 2.5mm jack, the one in particular I'm thinking of looks something like the following:
![image](https://user-images.githubusercontent.com/9312603/163890202-a68f94ed-850a-49bb-b872-1f2839f9c049.png)
Would the above wiring diagram work for your library to send zoom in/out commands? Can you recommend a wiring diagram for a zoom in/out use-case?

**Comment by sensslen** [comment]
The library implements the lanc protocol and this does not depend on any particular wiring. For the diagram you show: it seems plausible.
