### ISSUE TITLE
Example Programs

### ISSUE THREAD

**Issue by mattv8** [sensslen/LibLanc#5]
Do you have any examples of scripts using your library that you can provide for some basic commands like zoom in/out? Aperature fast/slow? Etc.?

**Comment by sensslen** [comment]
The library implements the lanc protocol and this does not depend on any particular wiring. For the diagram you show: it seems plausible.

**Comment by mattv8** [comment]
I appreciate the info, thank you! I see the Arduino library listed here: [https://www.arduino.cc/reference/en/libraries/liblanc/](https://www.arduino.cc/reference/en/libraries/liblanc/). Posting so it is accessible to others.
