### ISSUE TITLE
Is there have protocol Atomos Ninja V connect with lanc?

### ISSUE THREAD

**Issue by kertkalvik** [sensslen/LibLanc#7]
Is there have protocol Atomos Ninja V connect with lanc?
I would to record without any cameras, only record to Ninja V.

**Comment by sensslen** [comment]
Hi @kertkalvik, I don‘t really understand your question. I don‘t know about the Ninja V. If it has a lanc input port, it can receive commands from this library. The commands available in the library can be expanded. I can assist you adding new commands - please first make sure you find the necessary commands and figure out the hardware you require…

**Comment by sensslen** [comment]
Closing as the issue author seems to have no interest in providing additional information
